from setuptools import find_packages, setup

setup(name='kissan_migo',
      version='0.0.1',
      author='teach_to_grow',
      packages=find_packages(where='src', exclude=['tests']),
      package_dir={'':'src'},
      install_requires=['geopandas',
                        'pandas',
                        'ipykernel',
                        'earthengine-api',
                        'matplotlib',
                        'tqdm',
                        'seaborn',
                        'scipy',
                        'scikit-learn',
                        'termcolor~=2.3.0',
                        'steamship==2.17.7',
                        'steamship-langchain',
                        'earthengine-api',
                        'shapely',
                        'rasterio',
                        'openai',
                        'google-search-results',
                        'ipyleaflet',
                        'psycopg2'],
    include_package_data=True)
